[font]
size = 11.0
[font.normal]
family= "Fira Code"
style= "Regular"
[font.italic]
family= "Fira Code"
style= "Italic"
[font.bold]
family= "Fira Code"
style= "Bold"
[font.bold_italic]
family= "Fira Code"
style= "Bold Italic"

  # # The bold font face
  # bold:
  #   family: Fira Code
  #   # Style can be specified to pick a specific face.
  #   style: Bold
  #
  # # The italic font face
  # italic:
  #   family: Fira Code
  #   # Style can be specified to pick a specific face.
  #   style: Italic

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

# for ctrl+number bindings in tmux
[keyboard]
bindings= [
  {key="Key0", mods= "Control", chars= "\u001b[48;5u" },
  {key="Key1", mods= "Control", chars= "\u001b[49;5u" },
  {key="Key2", mods= "Control", chars= "\u001b[50;5u" },
  {key="Key3", mods= "Control", chars= "\u001b[51;5u" },
  {key="Key4", mods= "Control", chars= "\u001b[52;5u" },
  {key="Key5", mods= "Control", chars= "\u001b[53;5u" },
  {key="Key6", mods= "Control", chars= "\u001b[54;5u" },
  {key="Key7", mods= "Control", chars= "\u001b[55;5u" },
  {key="Key8", mods= "Control", chars= "\u001b[56;5u" },
  {key="Key9", mods= "Control", chars= "\u001b[57;5u" }
]
